FROM python:3.12.3-slim

# Set the working directory
WORKDIR /opt/render/project/src

# Copy the entire project
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Add current directory to Python path
ENV PYTHONPATH=/opt/render/project/src

# Debug: List contents to verify files
RUN ls -la service/

EXPOSE 80

# Set the default command
CMD ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:80", "service.service:app"]
